---
# title: "Anshuman Mishra"
toc: false
# page-layout: full
---

Thanks for dropping by on this little corner of internet. This is Anshuman.

I work as as an AI consultant helping startups and companies build AI-native products. 
I specialize in working with large language models and I have work at the intersection of LLMs, agent frameworks and backend.


### Who I’m Working With (Client companies)

- **Google** → Supporting Large Language Models in [KerasHub](https://github.com/keras-team/keras-hub), implementing them from scratch and writing technical deep-dives on using them.

### Previous Clients (Companies):

- **W&B** → I focused on creating clear and compelling educational content for the machine learning community. I wrote in-depth articles, tutorials, and guides explaining complex ML concepts and demonstrating best practices using the W&B platform.


### Previously led Applied ML at

**FlipAI** → Fifth employee of the company and 2nd **Machine Learning Engineer** hired.  My work involved the end-to-end ML lifecycle, from data preprocessing and model training to deployment and monitoring of core AI features. I also spent quite some time designing, building, and deploying applications & feature in a fast-paced production environment as per customer needs.

**Google** → Got selected to work with Tensorflow and Keras team through Google Summer of Code Program. Mainly worked on KerasHub (then KerasNLP), implementing models like Llama2, GPT NeoX from scratch and writing technical articles.

**BNY Mellon** → As a Data Science Intern, I gained hands-on experience within the financial services industry. My responsibilities included analyzing large datasets to uncover insights, building predictive models, and presenting my findings to support data-driven decision-making.

**Amazon** → During my internship at Amazon, I contributed to a team responsible for developing large-scale software systems. This experience provided a strong foundation in the software development lifecycle, including coding, debugging, and working with cloud infrastructure to deliver a project feature.


###

I am also [Google Developer Expert]((https://g.dev/anshuizme)) in Machine Learning and Google Cloud Platform.


