---
title: Authoring
aliases: 
  - /authoring
toc: false
---
Co-authored a book  [Hands-On Python Deep Learning for the Web](https://www.google.com/url?q=https%3A%2F%2Fwww.packtpub.com%2Fin%2Fdata%2Fhands-on-python-deep-learning-for-web&sa=D&sntz=1&usg=AFQjCNFMYAvFS-WzTymOqO7XyzZtdmWV0Q)  with  [Anubhav Singh](http://www.google.com/url?q=http%3A%2F%2Fxprilion.com&sa=D&sntz=1&usg=AFQjCNET_hwCDFMpPXSqwmzfw4HxevAq_A).

Authored the following liveProjects with [Manning](https://www.manning.com/):  

* [Use Machine Learning to Detect Phishing Websites](https://www.manning.com/liveproject/use-machine-learning-to-detect-phishing-websites?a_aid=pyimagesearch&a_bid=643ce05e) 
* [Summarize News Articles with NLP and TensorFlow](https://www.manning.com/liveproject/summarize-news-articles-with-nlp-and-tensorflow?a_aid=pyimagesearch&a_bid=643ce05e) (with [Souradip Chakraborty](https://www.linkedin.com/in/souradip-chakraborty/)) 

Authored two DataCamp Projects ([Predicting Credit Card Approvals](https://datacamp.pxf.io/doyrOM) and [Analyze International Debt Statistics](https://datacamp.pxf.io/MXKEAJ)) and a DataCamp Practice Pool on [Advanced Deep Learning with Keras](https://practice.datacamp.com/p/217?tap_a=5644-dce66f&tap_s=357540-5b28dd). 

Below are the blogs, articles, and tutorials I have written on Data Science, Machine Learning, and more. I am fortunate enough 
to collaborate with  amazing folks from all around the globe.

### [Weights&Biases](https://wandb.ai/)

-   [Supercharge KerasNLP Models with Wandb](https://wandb.ai/shivance/keras-nlp-x-wandb/reports/Supercharge-KerasNLP-Models-with-Wandb--Vmlldzo1Mjk1NjI2)
-   [Generating High-quality Images with SD.Next, HuggingFace Diffusers and W&B](https://wandb.ai/ml-colabs/automatic/reports/Generating-High-quality-Images-with-SD-Next-HuggingFace-Diffusers-and-W-B--Vmlldzo1NTYzMzQy)

### [Keras](https://www.keras.io/)

-   [Data Parallel Training with KerasNLP](https://keras.io/examples/nlp/data_parallel_training_with_keras_nlp/)
-   [Semantic Similarity with KerasNLP](https://keras.io/examples/nlp/semantic_similarity_with_keras_nlp/)
-   [Pretraining a Transformer from scratch with KerasNLP](https://keras.io/guides/keras_nlp/transformer_pretraining/)

### [Kaggle](https://www.keras.io/)

-   [Supercharge KerasNLP Models with Wandb](https://www.kaggle.com/code/shivanshuman/supercharge-kerasnlp-models-with-wandb)
-   [One Stop EDA](https://www.kaggle.com/code/shivanshuman/one-stop-eda)
-   [Kaggle T4x2 multi-gpu training G2Net](https://www.kaggle.com/code/shivanshuman/kaggle-t4x2-multi-gpu-training-g2net)
-   [LB:0.23 Ensemble {CatBoost, XGBoost, LightGBM}](https://www.kaggle.com/code/shivanshuman/lb-0-23-ensemble-catboost-xgboost-lightgbm)
-   [LightGBM + Optuna Baseline](https://www.kaggle.com/code/shivanshuman/lightgbm-optuna-baseline)

### [Medium](https://medium.com)

-   [Interview with 2x Kaggle Grandmaster, Data Science Manager at Emirates NBD: Ravi Ramakrishnan](https://shivance.medium.com/interview-with-2x-kaggle-grandmaster-data-science-manager-at-emirates-nbd-ravi-ramakrishnan-3308a3936c07)
-   [Flux.jl is so flexible — Deep Learning in Julia](https://juliazoid.com/fluxible-unet-c71e411c8b2d)
-   [Kaggle x Julia : Advanced House Price Prediction : EDA](https://shivance.medium.com/kaggle-x-julia-advanced-house-price-prediction-eda-1124b9a96f97)



[^1]:[About Neural ODE : Using Torchdiffeq with Deepchem](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/About_nODE_Using_Torchdiffeq_in_Deepchem.ipynb).
