---
title: Interviews
aliases: 
  - /interviews
toc: false
---

The purpose of conducting these interviews is to mainly **get insights about the real-world project experiences, perspectives on learning new things**, some fun facts and thereby enriching the communities in the process. I sincerely thank the interviewees for taking the time out from their busy schedules and for agreeing to do these interviews. Here are the interviews I have done so far -

-   [An Interview with **Ravi Ramakrishnan**, Kaggle Grandmaster](https://shivance.medium.com/interview-with-2x-kaggle-grandmaster-data-science-manager-at-emirates-nbd-ravi-ramakrishnan-3308a3936c07) (joint work with [Abheesht Sharma](https://www.linkedin.com/in/anshuizme/))
-   [An Interview with **Rajaswa Patil**, AI Research Associate at Postman Labs](https://medium.com/@sharmabhee/interview-with-rajaswa-patil-ai-researcher-at-postman-labs-4c4537f98ee) (joint work with [Abheesht Sharma](https://www.linkedin.com/in/anshuizme/))
-   [An Interview with **Matthew Watson**, Senior Software Engineer, Google](https://shivance.medium.com/interview-with-matthew-watson-keras-team-google-a5df3913ab95) (joint work with [Abheesht Sharma](https://www.linkedin.com/in/anshuizme/))
-   [An Interview with Aakash Kumar Nain, MLE at Merlyn Minds](https://medium.com/ai-chronicles/interview-with-aakash-kumar-nain-mle-at-merlyn-minds-785f0f2e147b) (joint work with [Abheesht Sharma](https://www.linkedin.com/in/anshuizme/))

I have had an amazing time interviewing these incredible folks and I am grateful to them. For other competing priorities, I am discontinuing the series for an indefinite period. If you enjoy reading through interviews like these, you might want to check out the [**Machine Learning Street Talk**](https://www.youtube.com/channel/UCMLtBahI5DMrt0NPvDSoIRQ) podcast on YouTube.  
