---
title: OpenSource Contributions
aliases: 
  - /opensource_contributions
toc: false
---


### [Highlights]

- [KerasNLP - Add Llama Backbone](https://github.com/keras-team/keras-nlp/pull/1203)
- [KerasNLP - Port GPTNeoX to KerasCore](https://github.com/keras-team/keras-nlp/pull/1137)
- [KerasNLP - Adding GPTNeoXBackbone](https://github.com/keras-team/keras-nlp/pull/1056)
- [KerasNLP - Generic RotaryEmbedding Layer](https://github.com/keras-team/keras-nlp/pull/1180)
- [Keras - Add rsqrt to ops API](https://github.com/keras-team/keras-core/pull/708)
- [Keras - Add rms_scaling in LayerNormalization](https://github.com/keras-team/keras-core/pull/726)
- [FluxML - Adding UNet Model](https://github.com/FluxML/Metalhead.jl/pull/210)
- [Deepchem - Porting CNN from TF ➡️ PyTorch ](https://github.com/deepchem/deepchem/pull/2963)
- [Deepchem - Neural ODE tutorial 📚](https://github.com/deepchem/deepchem/pull/2859)

### [All Contributions]

#### [keras-nlp](https://github.com/keras-team/keras-nlp)

- [Fix RotaryEmbedding import](https://github.com/keras-team/keras-nlp/pull/1217)
- [Fix Autograph error with perplexity metric](https://github.com/keras-team/keras-nlp/pull/1211)
- [Fix ModuleNotFoundError keras_nlp.models.xlnet](https://github.com/keras-team/keras-nlp/pull/1204)
- [Port BeamSampler to core](https://github.com/keras-team/keras-nlp/pull/1181)
- [Add compute_output_shape to tokenizer](https://github.com/keras-team/keras-nlp/pull/1166)
- [Refactor RotaryEmbedding and GPTNeoXAttention](https://github.com/keras-team/keras-nlp/pull/1101)
- [Add GPTNeoXPreprocessor](https://github.com/keras-team/keras-nlp/pull/1093)
- [Add an XLMRobertaMaskedLM task model](https://github.com/keras-team/keras-nlp/pull/950)
- [Speed up default RoBERTa testing roughly 3x](https://github.com/keras-team/keras-nlp/pull/897)
- [Adding XXBackboneTPUTests](https://github.com/keras-team/keras-nlp/pull/839)
- [Default compilation for Albert, Distilbert, Roberta MaskedLM](https://github.com/keras-team/keras-nlp/pull/833)
- [Call super.config() in BartBackbone's get_config()](https://github.com/keras-team/keras-nlp/pull/818)
- [Add API exports for tokenizers documented on keras.io](https://github.com/keras-team/keras-nlp/pull/817)
- [Add API exports for metrics documented on keras.io](https://github.com/keras-team/keras-nlp/pull/816)
- [Add API exports for samplers documented on keras.io](https://github.com/keras-team/keras-nlp/pull/815)
- [Add API exports for models documented on keras.io](https://github.com/keras-team/keras-nlp/pull/814)
- [Adding an AlbertMaskedLM task + Fix Projection layer dimension in MaskedLMHead](https://github.com/keras-team/keras-nlp/pull/725)
- [Add an add_prefix_space Arg in BytePairTokenizer](https://github.com/keras-team/keras-nlp/pull/715)
- [Move from_preset to base tokenizer classes](https://github.com/keras-team/keras-nlp/pull/673)
- [Add AlbertClassifier](https://github.com/keras-team/keras-nlp/pull/668)
- [Add Llama Backbone](https://github.com/keras-team/keras-nlp/pull/1203)
- [Port GPTNeoX to KerasCore](https://github.com/keras-team/keras-nlp/pull/1137)
- [Adding GPTNeoXBackbone](https://github.com/keras-team/keras-nlp/pull/1056)
- [Generic RotaryEmbedding Layer](https://github.com/keras-team/keras-nlp/pull/1180)


#### [keras-core](https://keras.io/keras_3/)

- [Add rsqrt to ops API](https://github.com/keras-team/keras-core/pull/708)
- [Add rms_scaling in LayerNormalization](https://github.com/keras-team/keras-core/pull/726)

#### [keras-io](https://keras.io)

- [Port [KerasNLP] Transformer Pretraining guide to multi-backend Keras](https://github.com/keras-team/keras-io/pull/1438)
- [fixing getting started guide kerasnlp](https://github.com/keras-team/keras-io/pull/1414)
- [Add example : Data Parallel Training with KerasNLP](https://github.com/keras-team/keras-io/pull/1395)
- [Add Semantic Similarity with KerasNLP tutorial](https://github.com/keras-team/keras-io/pull/1299)

#### [h2o-llmstudio](https://github.com/h2oai/h2o-llmstudio)

- [add: safe serialization while pushing to hf](https://github.com/h2oai/h2o-llmstudio/pull/221)

#### [flux-ml](https://github.com/FluxML/Metalhead.jl)

- [Adding UNet Model](https://github.com/FluxML/Metalhead.jl/pull/210)

#### [optax](https://github.com/google-deepmind/optax)

- [added typing to linear_algebra.py](https://github.com/google-deepmind/optax/pull/413)

#### [deepchem](https://github.com/deepchem/deepchem)

- [:octocat: Porting CNN, TF ➡️ PyTorch ](https://github.com/deepchem/deepchem/pull/2963)
- [:octocat: Fixed potential bug in deepchem's CNN implementation](https://github.com/deepchem/deepchem/pull/2964)
- [added neural ode tutorial 📚](https://github.com/deepchem/deepchem/pull/2859)
- [Fixing load_qm7_from_mat() not found](https://github.com/deepchem/deepchem/pull/2988)
